# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

test_that("add_info_to_cleaning_log works", {
  expect_true(inherits(add_info_to_cleaning_log, "function")) 
})
