# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

test_that("create_duration_from_audit_with_start_end works", {
  expect_true(inherits(create_duration_from_audit_with_start_end, "function")) 
})
