# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

test_that("check_percentage_missing works", {
  expect_true(inherits(check_percentage_missing, "function")) 
})
