# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

test_that("add_duration_from_audit works", {
  expect_true(inherits(add_duration_from_audit, "function")) 
})
