# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

test_that("create_xlsx_cleaning_log works", {
  expect_true(inherits(create_xlsx_cleaning_log, "function")) 
})
