# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

test_that("auto_sm_parent_children works", {
  expect_true(inherits(auto_sm_parent_children, "function")) 
})
