# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

test_that("create_duration_from_audit_sum_all works", {
  expect_true(inherits(create_duration_from_audit_sum_all, "function")) 
})
