# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand



# Unit test for add_ridl() using testthat
# 
# context("add_ridl()")
# 
# # Create mock objects to use in the test
# ridl <- "testRidl"
# datafolder <- "data"
# form <- "form.xlsx"
# namethisfile <- "testFile"
# visibility <- "public"
# stage <- "explo_initial"
# 
# # Create test for function
# test_that("add_ridl() creates the right resources", {
#   expect_true(add_ridl(ridl, datafolder, form, namethisfile, visibility, stage))
# })

# test_that("add_ridl works", {   expect_true(inherits(add_ridl, "function")) })
