# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

test_that("create_formatted_choices works", {
  expect_true(inherits(create_formatted_choices, "function")) 
})
