# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

test_that("check_logical_with_list works", {
  expect_true(inherits(check_logical_with_list, "function")) 
})
