# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' Adds duration from the audit file
#'
#' Wrapper around create_duration_from_audit_with_start_end and
#' create_duration_from_audit_sum_all to add the duration to the dataset.
#'
#' @param dataset dataset to add the duration
#' @param col_name_prefix string character to be used for the prefix of new columns
#' @param uuid_column uuid column in the dataset. Default is uuid.
#' @param audit_list list of dataframe that are the audit file with the uuid of
#' each interview as name of the dataframe.
#' @param start_question character vector use for the starting question (optional)
#' @param end_question character vector use for the ending question (optional)
#' @param sum_all TRUE or FALSE if to add the time with sum all duration
#'
#' @return return the dataset with durations column added
#' @export
#' @examples
#'  
#' list_audit <- list(
#'   uuid1 = data.frame(
#'     event = c("form start", rep("question", 5)),
#'     node = c("", paste0("/xx/question", 1:5)),
#'     start = c(
#'       1661415887295, 1661415887301,
#'       1661415890819, 1661415892297,
#'       1661415893529, 1661415894720
#'     ),
#'     end = c(
#'       NA, 1661415890790, 1661415892273,
#'       1661415893506, 1661415894703,
#'       1661415896452
#'     )
#'   ),
#'   uuid2 = data.frame(
#'     event = c("form start", rep("question", 5)),
#'     node = c("", paste0("/xx/question", 1:5)),
#'     start = c(
#'       1661415887295, 1661415887301, 1661415890819,
#'       1661415892297, 1661415893529, 1661415894720
#'     ),
#'     end = c(
#'       NA, 1661415890790, 1661415892273,
#'       1661415893506, 1661415894703, 1661415896452
#'     )
#'   )
#' )
#'
#' some_dataset <- data.frame(
#'   X_uuid = c("uuid1", "uuid2"),
#'   question1 = c("a", "b"),
#'   question2 = c("a", "b"),
#'   question3 = c("a", "b"),
#'   question4 = c("a", "b"),
#'   question5 = c("a", "b")
#' )
#'
#'
#' add_duration_from_audit(some_dataset,
#'                         uuid_column = "X_uuid",
#'                         audit_list = list_audit)|>
#'   knitr::kable()  
#'
#'
#' add_duration_from_audit(some_dataset,
#'                         uuid_column = "X_uuid", 
#'                         audit_list = list_audit,
#'                         start_question = "question1",
#'                         end_question = "question3",
#'                         sum_all = FALSE) |>
#'   knitr::kable()  
#'
#' add_duration_from_audit(some_dataset,
#'                         uuid_column = "X_uuid", 
#'                         audit_list = list_audit,
#'                         start_question = "question1",
#'                         end_question = "question3",
#'                         sum_all = TRUE) |>
#'   knitr::kable()  

add_duration_from_audit <- function(dataset,
                                    col_name_prefix = "duration_audit",
                                    uuid_column = "uuid",
                                    audit_list,
                                    start_question = NULL,
                                    end_question = NULL,
                                    sum_all = TRUE) {
  # checks input
  if (is.null(start_question) & !is.null(end_question)) {
    stop("start_question is missing")
  }
  if (!is.null(start_question) & is.null(end_question)) {
    stop("end_question is missing")
  }
  if (!is.null(start_question) & !is.null(end_question)) {
    new_names_start_end <- paste0(col_name_prefix, c("_start_end_ms", "_start_end_minutes"))
    if (any(new_names_start_end %in% names(dataset))) {
      msg <- glue::glue(col_name_prefix, " seems to be already used as name in your dataset.")
      stop(msg)
    }
  }

  if (sum_all) {
    new_names_sum_all <- paste0(col_name_prefix, c("_sum_all_ms", "_sum_all_minutes"))
    if (any(new_names_sum_all %in% names(dataset))) {
      msg <- glue::glue(col_name_prefix, " seems to be already used as name in your dataset.")
      stop(msg)
    }
  }

  # calculate duration for each audit file
  if (!is.null(start_question) & !is.null(end_question)) {
    duration_with_start_end <- audit_list %>%
      purrr::map(~ create_duration_from_audit_with_start_end(.x,
        start_question = start_question,
        end_question = end_question
      )) %>%
      purrr::set_names(names(audit_list)) %>%
      do.call(rbind, .) %>%
      `names<-`(new_names_start_end) %>%
      dplyr::mutate(uuid = row.names(.))
  }

  if (!uuid_column %in% names(dataset)) {
    msg <- glue::glue(uuid_column, " variable cannot be found in the dataset.")
    stop(msg)
  }

  if (all(!names(audit_list) %in% dataset[[uuid_column]])) {
    stop("It seems no uuid are found as name of any data frame of audit list, make sure the data frame are saved with the uuid as name.")
  }

  audit_check <- audit_list %>%
    purrr::map_lgl(function(xx) {
      all(c("node", "start", "end", "event") %in% names(xx))
    }) %>%
    all()
  if (!audit_check) {
    stop("Some columns are missing in the audits, please make sure to have at least event, node, start, end")
  }

  if (sum_all) {
    duration_with_sum_all <- audit_list %>%
      purrr::map(create_duration_from_audit_sum_all) %>%
      purrr::set_names(names(audit_list)) %>%
      do.call(rbind, .) %>%
      `names<-`(new_names_sum_all) %>%
      dplyr::mutate(uuid = row.names(.))
  }

  if (exists("duration_with_sum_all")) {
    dataset <- dataset %>%
      dplyr::left_join(duration_with_sum_all, by = stats::setNames("uuid", uuid_column))
  }

  if (exists("duration_with_start_end")) {
    dataset <- dataset %>%
      dplyr::left_join(duration_with_start_end, by = stats::setNames("uuid", uuid_column))
  }

  return(dataset)
}
