# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' @name auto_sm_parent_child
#' @rdname auto_sm_parent_child
#' @title detect and group together select multiple parent and children columns
#' @description `auto_sm_parent_children` is mean to detect select multiple parent columns & children columns in a way that does
#' not rely on the XLSForm as the input
#' @param dataset dataset to correct
#' @param sm_separator Separator for choice multiple questions. The default is "."
#'  If using read_csv to read in data the separator will most likely be '/' where as if using read.csv it will likely be '.'
#' @return a data frame containing the the child select multiple columns alongside there parents and
#' a log with all changes recorded.
#' @export
#' @examples
#' #auto_sm_parent_children()


auto_sm_parent_children <- function(dataset, sm_separator = ".") {
  sm_parents <- auto_detect_sm_parents(dataset, sm_separator)
  sm_child <- dataset %>%
    dplyr::select(dplyr::starts_with(glue::glue("{sm_parents}{sm_separator}"))) %>%
    colnames()
  dplyr::tibble(sm_parent = sub(glue::glue(".[^\\{sm_separator}]*$"), "", sm_child),
                sm_child)
}
