# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' Check if duration is outside of a range
#'
#' Check if value is strictly inferior of the lower threshold or strictly
#' superior of the higher threshold.
#'
#' @param dataset a dataset to be check as a dataframe or a list with the
#' dataframe stored as "checked_dataset"
#' @param column_to_check string character with the name of the duration column
#' @param uuid_column uuid column in the dataset. Default is uuid.
#' @param log_name character string with name to give to the log
#' @param lower_bound lower value of the range (strictly inferior to)
#' @param higher_bound higher value of the range (strictly superior to)
#'
#' @return return a list with the dataset checked stored as checked_dataset and
#' a dataframe with the duration log
#' @export
#' @examples
#'
#' testdata <- data.frame(
#'   uuid = c(letters[1:7]),
#'   duration_audit_start_end_ms = c(
#'     2475353, 375491, 2654267, 311585, 817270,
#'     2789505, 8642007
#'   ),
#'   duration_audit_start_end_minutes = c(41, 6, 44, 5, 14, 46, 144)
#' )
#'  
#' check_duration(testdata,
#'                 column_to_check = "duration_audit_start_end_minutes") |>
#'   knitr::kable()  
#'  
#' check_duration( testdata,
#'                 column_to_check = "duration_audit_start_end_ms",
#'                 lower_bound = 375490,
#'                 higher_bound = 8642000) |>
#'   knitr::kable()  
#'  
#' testdata %>%
#'   check_duration(column_to_check = "duration_audit_start_end_minutes") %>%
#'   check_duration( column_to_check = "duration_audit_start_end_ms",
#'                   log_name = "duration_in_ms",
#'                   lower_bound = 375490,
#'                   higher_bound = 8642000  )|>
#'   knitr::kable()  

check_duration <- function(dataset,
                           column_to_check,
                           uuid_column = "uuid",
                           log_name = "duration_log",
                           lower_bound = 25,
                           higher_bound = 90) {
  if (is.data.frame(dataset)) {
    dataset <- list(checked_dataset = dataset)
  }
  if (!("checked_dataset" %in% names(dataset))) {
    stop("Cannot identify the dataset in the list")
  }

  if (!(column_to_check %in% names(dataset[["checked_dataset"]]))) {
    msg <- glue::glue("Cannot find ", column_to_check, " in the names of the dataset")
    stop(msg)
  }

  log <- dataset[["checked_dataset"]] %>%
    dplyr::mutate(duration_check = !!rlang::sym(column_to_check) < lower_bound |
      !!rlang::sym(column_to_check) > higher_bound) %>%
    dplyr::filter(duration_check) %>%
    dplyr::select(dplyr::all_of(c(uuid_column, column_to_check))) %>%
    dplyr::mutate(
      question = column_to_check,
      issue = "Duration is lower or higher than the thresholds"
    ) %>%
    dplyr::rename(
      old_value = !!rlang::sym(column_to_check),
      uuid = !!rlang::sym(uuid_column)
    )

  dataset[[log_name]] <- log
  return(dataset)
}
