# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' Check the percentages of missing value
#'
#' The function will flag if a survey for its missing values. The missing values column can be created
#' with add_percentage_missing and the values are flagged with check_outliers.
#'
#' @param dataset a dataset to be check as a dataframe or a list with the
#' dataframe stored as "checked_dataset".
#' @param uuid_column uuid column in the dataset. Default is "uuid".
#' @param column_to_check string character with the name of the columns to check. Default is
#' "percentage_missing"
#' @param log_name name of the log of flagged value, default is percentage_missing_log
#' @param strongness_factor Strongness factor define how strong your outliers will be. The default is 3.
#' @return return a list with the dataset checked stored as checked_dataset and
#' a dataframe with the flagged values log
#' @export
#'
#' @seealso [cleaningtools::add_percentage_missing()], [cleaningtools::check_outliers()]
#' @examples
#'  
#' # Adding the percentage missing first
#' data_example <- data.frame(
#'   uuid = letters[1:3],
#'   col_1 = c(1:3),
#'   col_2 = c(NA, NA, "expenditures"),
#'   col_3 = c("with need", NA, "with need"),
#'   col_4 = c("food health school", NA, "food"),
#'   col_4.food = c(1, NA, 1),
#'   col_4.health = c(1, NA, 0),
#'   col_4.school = c(1, NA, 0)
#' )
#'
#' data_example <- data_example %>%
#'     add_percentage_missing()
#'
#' data_example %>% 
#'   check_percentage_missing() |>
#'   knitr::kable()
#'
#'
#' # With a dataset that already has a percentage missing
#' data_example2 <- data.frame(
#'   uuid = letters,
#'   any_cols = LETTERS,
#'   any_number = 1:26,
#'   percentage_missing = c(rep(.05, 25), .99)
#' )
#'
#' data_example2 %>% 
#'   check_percentage_missing() |>
#'   knitr::kable()

check_percentage_missing <- function(dataset,
                                     uuid_column = "uuid",
                                     column_to_check = "percentage_missing",
                                     strongness_factor = 2,
                                     log_name = "percentage_missing_log") {
  if (is.data.frame(dataset)) {
    dataset <- list(checked_dataset = dataset)
  }
  if (!("checked_dataset" %in% names(dataset))) {
    stop("Cannot identify the dataset in the list")
  }

  if (!(uuid_column %in% names(dataset[["checked_dataset"]]))) {
    msg <- glue::glue("Cannot find ", uuid_column, " in the names of the dataset")
    stop(msg)
  }

  if (!(column_to_check %in% names(dataset[["checked_dataset"]]))) {
    msg <- glue::glue("Cannot find ", column_to_check, " in the names of the dataset")
    stop(msg)
  }

  log <- dataset[["checked_dataset"]] %>%
    dplyr::select(dplyr::all_of(c(uuid_column, column_to_check))) %>%
    check_outliers(uuid_column = uuid_column, strongness_factor = strongness_factor)

  log[["potential_outliers"]] <- log[["potential_outliers"]] %>%
    dplyr::mutate(dplyr::across(.cols = dplyr::everything(), .fns = as.character),
      issue = "Percentages of missing values from this survey is different from others"
    )

  dataset[[log_name]] <- log[["potential_outliers"]]

  return(dataset)
}
