# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' Check if the input passed to the check_others function is correct
#'
#' @param dataset dataset to be check as a dataframe or a list with the dataframe stored as "checked_dataset"
#' @param uuid_column uuid column in the dataset. Default is uuid.
#' @param columns_to_check Columns to include in the checks
#'
#' @return nothing
#' @export
#'
#' @examples
#' #check_others_checks()

check_others_checks <- function(dataset, uuid_column, columns_to_check) {
  if (!(uuid_column %in% names(dataset))) {
    stop("uuid column is missing")
  }

  if (is.null(columns_to_check)) {
    stop("provide the list of follow up questions")
  }

  if (!is.null(columns_to_check) & any(!columns_to_check %in% names(dataset))) {
    stop("at least one variable is missing from the dataset")
  }

  if (!is.null(columns_to_check) & any(!columns_to_check %in% names(dataset))) {
    stop("at least one variable is missing from the dataset")
  }
}

