# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' Coerce numeric values to character, without scientific noting and NA are kept as NA.
#'
#' @param x a value to convert
#'
#' @return x as character
#' @export
#' @examples
#' coerce_to_character(c("a", NA))
#' coerce_to_character(c(1, 10000000, NA))

coerce_to_character <- function(x) {
  format(x, scientific = F, justify = "none", trim = T) %>%
    dplyr::na_if("NA")
}

