# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' Create a Validation List for Data Entry
#'
#' This function generates a validation list to be used for data entry validation.
#' It combines predefined validation lists with dynamically formatted choices derived from
#' the `choices` and `tool` parameters. The resulting dataframe is intended to provide
#' structured and valid choices for various question types.
#'
#' @param choices A dataframe representing the Kobo choices sheet.
#'        Expected to have at least the columns `list_name` and `name`.
#' @param tool A dataframe representing the Kobo survey sheet.
#'        Expected to have at least the columns `type` and `name`.
#'
#' @return A dataframe where each column corresponds to a choice list for a specific question.
#'         Each row contains a valid choice for the question.
#'
#' @export
#' @examples
#' # Assume choices_df and tool_df are sample dataframes that fit the expected structure.
#' #validation_list <- create_validation_list(choices, tool)
create_validation_list <- function(choices, tool) {
  new_lists <- list(
    c("change_type_validation", "change_response;\nblank_response;\nremove_survey;\nno_action"),
    c("binaries_sm_options_lgl", "FALSE;\nTRUE"),
    c("binaries_sm_options_num", "0;\n1")
    # c("_duplicates_","-- keep the survey --;\n-- delete the survey --"),
    # c("_action_","-- confirm --;\n-- update --;\n-- delete --")
  ) %>%
    do.call(rbind, .) %>%
    as.data.frame() %>%
    stats::setNames(c("name", "choices"))

  choicelist <- new_lists %>%
    dplyr::bind_rows(create_formatted_choices(choices, tool) %>%
      dplyr::select(name, choices))

  choice_validation <- choicelist %>%
    unique() %>%
    data.table::transpose() %>%
    stats::setNames(.[1, ]) %>%
    dplyr::slice(-1) %>%
    dplyr::mutate_all(~ stringr::str_split(., ";\n"))

  nrow_validation <- lapply(choice_validation, function(x) length(x[[1]])) %>%
    unlist() %>%
    max()

  data.val <- data.frame(matrix(NA, nrow = nrow_validation, ncol = 0))

  for (c in colnames(choice_validation)) {
    data.val <- data.val %>%
      dplyr::mutate(!!rlang::sym(c) := c(unlist(choice_validation[[c]]), rep(NA, nrow_validation - length(choice_validation[[c]][[1]]))))
  }

  return(data.val)
}
