# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' Calculate duration from audit between 2 questions
#'
#' The function will calculate time difference between the start of the
#' start_question and the end of the end_question.
#'
#' In case the node appear several time (if the value was changed or with a
#' select multiple) it will take the minimum for the start and the maximum for
#' the end.
#'
#' If a value is missing (skip logic or question not found), it will return -Inf
#'
#' @param audit_file a dataframe with a single audit file,
#' it needs start, end, node column
#' @param start_question character vector use for the starting question
#' @param end_question character vector use for the ending question
#'
#' @return A dataframe with the duration in ms and duration in minutes.
#' @export
#' @examples
#'
#' some_audit <- data.frame(
#'   event = c("form start", rep("question", 5)),
#'   node = c("", paste0("/xx/question", 1:5)),
#'   start = c(
#'     1661415887295, 1661415887301, 1661415890819,
#'     1661415892297, 1661415893529, 1661415894720
#'   ),
#'   end = c(
#'     NA, 1661415890790, 1661415892273,
#'     1661415893506, 1661415894703, 1661415896452
#'   )
#' )
#'
#'
#' create_duration_from_audit_with_start_end(some_audit,
#'                                           "question1", 
#'                                           "question3") |>
#'   knitr::kable()  

create_duration_from_audit_with_start_end <- function(audit_file, start_question, end_question) {
  df_start_subset <- audit_file[grepl(paste0("\\/(?:", start_question, ")$"), audit_file$node), ]
  start_question_df <- df_start_subset %>% dplyr::select(start)
  start_question_df <- min(start_question_df$start)

  df_end_subset <- audit_file[grepl(paste0("\\/(?:", end_question, ")$"), audit_file$node), ]
  end_question_df <- df_end_subset %>% dplyr::select(end)
  end_question_df <- max(end_question_df$end)

  duration_ms <- end_question_df - start_question_df
  duration_minutes <- round(duration_ms / 1000 / 60, 1)

  data.frame(
    duration_ms = duration_ms,
    duration_minutes = duration_minutes
  )
}
