# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' Calculate duration from audit summing all time
#'
#' Duration is the difference between the sum of all start and the sum of all end.
#' It ignores all node that are empty such as form_start, end screen, form save, etc.
#'
#' @param audit_file a dataframe with a single audit file,
#' it needs start, end, node column
#'
#' @return A dataframe with the duration in ms and duration in minutes.
#' @export
#' @examples
#'  
#' some_audit <- data.frame(
#'   event = c("form start", rep("question", 5)),
#'   node = c("", paste0("/xx/question", 1:5)),
#'   start = c(
#'     1661415887295, 1661415887301, 1661415890819,
#'     1661415892297, 1661415893529, 1661415894720
#'   ),
#'   end = c(
#'     NA, 1661415890790, 1661415892273,
#'     1661415893506, 1661415894703, 1661415896452
#'   )
#' )
#'
#' create_duration_from_audit_sum_all(some_audit)|>
#'   knitr::kable()  

create_duration_from_audit_sum_all <- function(audit_file) {
  audit_file <- audit_file %>% dplyr::filter(node != "")
  duration_ms <- sum(audit_file$end - audit_file$start)
  duration_minutes <- round(duration_ms / 1000 / 60, 1)
  data.frame(
    duration_ms = duration_ms,
    duration_minutes = duration_minutes
  )
}
