# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' Creates formatted workbook with openxlsx
#'
#' @param write_list List of dataframe
#' @param header_front_color Hexcode for header front color (default is white)
#' @param header_front_size Header front size (default is 12)
#' @param header_fill_color Hexcode for header fill color (default is red)
#' @param header_front Front name for header (default is Arial Narrow)
#' @param body_front Front name for body (default is Arial Narrow)
#' @param body_front_size Front size for body (default is 11)
#' @param column_for_color Column name in the dataframe which should be used for colorizing the cell. The default is null.
#'
#' @return A workbook
#' @export
#' @examples
#'  
#' checks_list <- cleaningtools::cleaningtools_raw_data |>
#'   check_pii(uuid_column = "X_uuid") |>
#'   check_duplicate(uuid_column = "X_uuid") |>
#'   check_value(uuid_column = "X_uuid") 
#'
#' create_combined_log(list_of_log = checks_list) |>
#'   create_formated_wb()

create_formated_wb <- function(write_list,
                               column_for_color = NULL,
                               header_front_size = 12,
                               header_front_color = "#FFFFFF",
                               header_fill_color = "#ee5859",
                               header_front = "Arial Narrow",
                               body_front = "Arial Narrow",
                               body_front_size = 11) {
  headerStyle <- openxlsx::createStyle(
    fontSize = header_front_size,
    fontColour = header_front_color,
    halign = "center",
    valign = "center",
    fontName = header_front,
    textDecoration = "bold",
    fgFill = header_fill_color,
    border = "TopBottomLeftRight ",
    borderColour = "#fafafa",
    wrapText = T
  )

  bodyStyle <- openxlsx::createStyle(
    fontSize = body_front_size,
    fontName = body_front,
    border = "TopBottomLeftRight ",
    borderColour = "#4F81BD",
    valign = "center",
    halign = "left"
  )

  wb <- openxlsx::createWorkbook()

  number_of_sheet <- length(write_list)

  for (i in 1:number_of_sheet) {
    dataset_name <- names(write_list[i])
    dataset <- write_list[[dataset_name]] |> as.data.frame()

    openxlsx::addWorksheet(wb, dataset_name)
    openxlsx::writeData(wb, sheet = i, dataset, rowNames = F)
    openxlsx::addFilter(wb, sheet = i, row = 1, cols = 1:ncol(dataset))
    openxlsx::freezePane(wb, sheet = i, firstCol = TRUE, firstRow = T)
    openxlsx::addStyle(wb, sheet = i, headerStyle, rows = 1, cols = 1:ncol(dataset), gridExpand = TRUE)
    openxlsx::addStyle(wb, sheet = i, bodyStyle, rows = 1:nrow(dataset) + 1, cols = 1:ncol(dataset), gridExpand = TRUE)
    openxlsx::setColWidths(wb, i, cols = 1:ncol(dataset), widths = 25)
    openxlsx::setRowHeights(wb, i, 1, 20)

    if (!is.null(column_for_color)) {
      u <- unique(dataset[[column_for_color]])

      for (x in u) {
        y <- which(dataset[[column_for_color]] == x)

        random.color <- randomcoloR::randomColor(1, luminosity = "light")

        style <- openxlsx::createStyle(
          fgFill = random.color,
          fontSize = body_front_size,
          fontName = body_front,
          border = "TopBottomLeftRight ",
          borderColour = "#4F81BD",
          valign = "center",
          halign = "left"
        )


        openxlsx::addStyle(wb, sheet = i, style, rows = y + 1, cols = 1:ncol(dataset), gridExpand = TRUE)
      }
    }
  }

  wb
}
