# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' Generate excel range to be used for the data validation formula in excel
#'
#' This function returns an Excel cell range for a given column in a dataframe.
#' The range is formatted for use in Excel functions or formulas and is prefixed
#' with the sheet name 'validation_rules'.
#'
#' @param variable The name of the column/question for which the Excel range is to be generated.
#' @param data.val A dataframe containing the column specified by `variable`.
#'
#' @return A string representing the Excel cell range containing all choices for the column `variable`
#'         in the sheet 'validation_rules'.
#'
#' @export
#' @examples
#'  # Assume df is a sample dataframe with a column named 'consent'.
#' #range_string <- create_col_range('consent', df)
create_col_range <- function(variable, data.val) {
  column.number <- which(colnames(data.val) == variable)
  all <- expand.grid(LETTERS, LETTERS)
  all <- all[order(all$Var1, all$Var2), ]
  alphabet <- c(LETTERS, do.call("paste0", all))
  col.excel <- alphabet[column.number]
  nrow <- nrow(data.val %>% dplyr::filter(!is.na(!!rlang::sym(variable))))
  range.vect <- c("$", col.excel, "$2:$", col.excel, "$", (nrow + 1))
  range <- paste(range.vect, sep = "", collapse = "")
  value.sheet <- paste("'validation_rules'!")
  value <- paste(value.sheet, range, sep = "", collapse = "")
  return(value)
}
