# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' Read all audit files from a zip
#'
#' @param audit_zip_path location to .zip file. It must contain .zip
#' @param dataset dataset to (optional)
#' @param uuid_column uuid column if a dataset is provided. It will only read the uuid
#' present in the dataset. It will only be used if a dataset is provided.
#'
#' @return A list with all the audits file read as they are.
#' @export
#' @examples
#' # create_audit_list("audit_path.zip")

create_audit_list <- function(audit_zip_path,
                              dataset = NULL,
                              uuid_column = "uuid") {
  list_of_files <- utils::unzip(audit_zip_path, list = TRUE) %>%
    dplyr::rename(path = Name) %>%
    dplyr::filter(stringr::str_detect(path, pattern = "audit.csv"))

  locatation_audit <- list_of_files %>%
    dplyr::pull(path) %>%
    stringr::str_split("/") %>%
    purrr::set_names(list_of_files$path) %>%
    purrr::map_dbl(~ which(stringr::str_detect(.x, "audit.csv"))) %>%
    unique()

  if (length(locatation_audit) != 1) {
    stop("Please check the audit zip, some folders are not following the same structure.")
  }

  all_uuid_df <- list_of_files %>%
    dplyr::select(path) %>%
    dplyr::rowwise() %>%
    dplyr::mutate(uuid = unlist(stringr::str_split(path, "/"))[[locatation_audit - 1]]) %>%
    dplyr::ungroup()

  if (!is.null(dataset)) {
    if (uuid_column %in% names(dataset) != 1) {
      msg <- glue::glue("The variable ", uuid_column, " cannot be identified in the dataset provided.")
      stop(msg)
    }
    look_up_vector <- dataset[[uuid_column]]

    if (any(!all_uuid_df$uuid %in% look_up_vector)) {
      msg <- glue::glue(nrow(all_uuid_df) - length(look_up_vector), " audit files are found but not in the dataset. They won't be read.")
      warning(msg)
    }

    all_uuid_df <- all_uuid_df %>%
      dplyr::filter(uuid %in% look_up_vector)
  }

  list_of_audits <- all_uuid_df$path %>%
    purrr::map(~ read.table(unz(audit_zip_path, filename = .x), header = TRUE, quote = "\"", sep = ",")) %>%
    purrr::set_names(all_uuid_df$uuid)

  if (!is.null(dataset)) {
    if (length(list_of_audits) < length(look_up_vector)) {
      to_add_vector <- look_up_vector[!look_up_vector %in% names(list_of_audits)]
      msg <- glue::glue(length(to_add_vector), " audit files were not found. They were added as empty dataframes.")
      warning(msg)
      to_add <- purrr::map(to_add_vector, function(xx) {
        list_of_audits[[1]] %>% dplyr::filter(event == "IWANTANEMPTYAUDIT")
      }) %>%
        purrr::set_names(to_add_vector)

      list_of_audits <- append(list_of_audits, to_add)
    }
  }

  return(list_of_audits)
}
