# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' Help to print log or message for the template
#'
#' @param log_to_print A data frame to print
#' @param message A message to print if the data frame is empty
#'
#' @return The data frame to print or an alternative message if the dataframe is empty
#' @export
#' @examples
#' #print_log(log_to_print, "No values flagged")
 
print_log <- function(log_to_print, message) {
  if(nrow(log_to_print) == 0) {
    cat(message)
  } else {
    log_to_print |> knit_big_table()
  }
}
