# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' check cleaning log
#' @param raw_dataset Raw dataset
#' @param raw_data_uuid_column uuid column in the raw dataset. Default is "uuid".
#' @param cleaning_log cleaning log (data.frame)
#' @param cleaning_log_uuid_column uuid column in the cleaning log. Default is "uuid".
#' @param cleaning_log_question_column column in cleaning log which specifies data set column to change
#' @param cleaning_log_new_value_column cleaning log column specifying the new correct value
#' @param cleaning_log_change_type_column column in cleaning log which specifies change type to be made
#' @param change_response_value values in change type column which should be changed to a new value.
#' @return cleaning log with only problematic entries and note specifying problem
#' @export
#' @examples
#' #review_cleaning_log()


review_cleaning_log <- function(raw_dataset,
                               raw_data_uuid_column = "uuid",
                               cleaning_log,
                               cleaning_log_uuid_column = "uuid",
                               cleaning_log_question_column,
                               cleaning_log_new_value_column,
                               cleaning_log_change_type_column,
                               change_response_value = "change_response") {
  
  cleaning_log[[cleaning_log_question_column]] <-
    cleaning_log[[cleaning_log_question_column]] %>% trimws()
  cleaning_log[[cleaning_log_new_value_column]] <-
    cleaning_log[[cleaning_log_new_value_column]] %>% trimws()


  assertthat::assert_that(cleaning_log_change_type_column %in% names(cleaning_log),
                          msg = "cleaning_log_change_type_column column not found in cleaning log")

  assertthat::assert_that(all(change_response_value %in% cleaning_log[[cleaning_log_change_type_column]]),
                          msg = "Value in change_response_value not found")

  cl_change_col_prob_df <- cleaning_log %>%
    dplyr::filter(!!rlang::sym(cleaning_log_change_type_column) %in% change_response_value) %>%
    dplyr::mutate(cl_prob = "question_does_not_exist") %>%
    dplyr::filter(!!rlang::sym(cleaning_log_question_column) %in% colnames(raw_dataset) == FALSE) %>%
    dplyr::select(cl_prob, dplyr::everything())

  cl_uuid_prob_df <- cleaning_log %>%
    dplyr::filter(!!rlang::sym(cleaning_log_uuid_column) %in% c(raw_dataset[[raw_data_uuid_column]], "all_data") == FALSE) %>%
    dplyr::mutate(cl_prob = "uuid_does_not_exist") %>%
    dplyr::filter(!!rlang::sym(cleaning_log_uuid_column) %in% raw_dataset[[raw_data_uuid_column]] == FALSE) %>%
    dplyr::select(cl_prob, dplyr::everything())

  na_change_type_prob_df <- cleaning_log %>%
    dplyr::filter(is.na(!!rlang::sym(cleaning_log_change_type_column))) %>%
    dplyr::mutate(cl_prob = "na_in_change_type") %>%
    dplyr::select(cl_prob, dplyr::everything())

  cl_problems_df <-
    dplyr::bind_rows(get0("cl_change_col_prob_df"), get0("cl_uuid_prob_df")) |>
    dplyr::bind_rows(get0("na_change_type_prob_df"))

  if (nrow(cl_problems_df) > 0) {
    print("cleaning log has issues, see output table")
  } else {
    cl_problems_df <- "no issues in cleaning log found"
  }
  return(cl_problems_df)
}

