# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' Verify if the Kobo survey dataframe is valid
#'
#' This function checks whether the provided Kobo survey dataframe meets certain criteria:
#' 1. It is a dataframe.
#' 2. It is not empty.
#' 3. It contains columns named "type" and "name".
#'
#' @param kobo_survey A dataframe representing the Kobo survey sheet.
#'
#' @return Logical. Returns `TRUE` if the dataframe meets all the criteria. Otherwise, it returns `FALSE`.
#'
#' @export
#' @examples
#'  
#' # Assume df_valid is a valid Kobo survey dataframe
#' df_valid <- data.frame(type = c("integer", "selecte_one yesno"), name = c("age", "consent"))
#' verify_valid_survey(df_valid) # should return TRUE
#'  
#' # Assume df_invalid lacks the required columns
#' df_invalid <- data.frame(column1 = c("integer", "selecte_one yesno"), column2 = c("age", "consent"))
#' verify_valid_survey(df_invalid) # should return FALSE

verify_valid_survey <- function(kobo_survey) {
  if (!is.data.frame(kobo_survey)) {
    return(F)
  }
  if (length(kobo_survey) == 0) {
    return(F)
  }
  if (!all(c("type", "name") %in% names(kobo_survey))) {
    return(F)
  }

  return(TRUE)
}
