# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' Verify if the Kobo choices dataframe is valid
#'
#' This function checks whether the provided Kobo choices dataframe meets certain criteria:
#' 1. It is a dataframe.
#' 2. It is not empty.
#' 3. It contains columns named "list_name" and "name".
#'
#' @param kobo_choices A dataframe representing the Kobo choices sheet.
#'
#' @return Logical. Returns `TRUE` if the dataframe meets all the criteria. Otherwise, it returns `FALSE`.
#'
#' @export
#' @examples
#'  
#' # Assume df_valid_choices is a valid Kobo choices dataframe
#' df_valid_choices <- data.frame(list_name = c("ChoiceA", "ChoiceB"), name = c("Option1", "Option2"))
#' verify_valid_choices(df_valid_choices) # should return TRUE
#'  
#' # Assume df_invalid_choices lacks the required columns
#' df_invalid_choices <- data.frame(column1 = c("ChoiceA", "ChoiceB"),
#'                                  column2 = c("Option1", "Option2"))
#' verify_valid_choices(df_invalid_choices) # should return FALSE

verify_valid_choices <- function(kobo_choices) {
  if (!is.data.frame(kobo_choices)) {
    return(F)
  }
  if (length(kobo_choices) == 0) {
    return(F)
  }
  if (!all(c("list_name", "name") %in% names(kobo_choices))) {
    return(F)
  }

  return(TRUE)
}
